[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_optimize = true
solc_via_ir = true
solc_optimize_runs = 200
remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@foundry-devops=lib/foundry-devops/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/'
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options




fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
    { access = "read", path = "./img/" },
]
